### ISSUE TITLE
Investigate Autoscaling with prometheus-adapter

### ISSUE THREAD

**Issue by jalaka** [AustrianDataLAB/IndieGameStream#12]
Investigate how to setup prometheus with kubernetes?

1. How to get the neccesary metrics (Numbers of workers runing/ Numbers of current users)
2. How do we configure the autoscaler?

https://github.com/kubernetes-sigs/prometheus-adapter

**Comment by stefancsukker** [comment]
in case metrics are not available for kubernetes:

 - download "components.yaml" from https://github.com/kubernetes-sigs/metrics-server/releases
 - execute: kubectl apply -f components.yaml
 - in case of error "cannot validate certificate for ***.***.***.*** (IP) add the following line ~L136:
 - "- --kubelet-insecure-tls"
 
 for a local kubernetes instance run "kubectl proxy"
 open localhost:8001
 it should show all the services including /metrics
 if you want to make sure the metrics are available run "curl 127.0.0.1:8001/metrics"
 
 next, add kubernetes to prometheus config (yaml):
 add it somewhere below scrape_configs:
   - job_name: 'kubernetes'
  
    scrape_interval: 5s
    
    static_configs:
      - targets: ['localhost:8001']
	  
	  
	  
check localhost:9090/targets -> it should show the kubernetes metrics endpoint


https://sysdig.com/blog/kubernetes-monitoring-prometheus/
contains info on how to monitor different kubernetes services

**Comment by stefancsukker** [comment]
- [ ] find out how to log the distinct requests from the workers

**Comment by stefancsukker** [comment]
prometheus is able to scrape stunner. metrics are **disabled** by default though
has to be enabled by setting **enableMetricsEndpoint** to true
see docs: [stunner documentation](https://docs.l7mp.io/en/v0.17.0/GATEWAY/#dataplane)
