### ISSUE TITLE
Api save & delete gamefile in Azure file storage

### ISSUE THREAD

**Issue by Intrpt** [AustrianDataLAB/IndieGameStream#25]
In the moment the api is just saving the metadata in the database.
- [x] check if the game is always just one file or multiple files.
- [x] save the gamefile(s) in the azure file storage location using azure rest api.
- [x] save the location of the files in the database
- [x] When deleting the game from the database, we also have to delete it from azure.

**Comment by Intrpt** [comment]
It is always just one file:
"[...]By using the libretro API, your program becomes a single library file, known as a 'libretro core'[...]" [See here](https://docs.libretro.com/start/understanding/#what-is-libretro)

**Comment by Intrpt** [comment]
https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=microsoft-entra-id

**Comment by Intrpt** [comment]
https://learn.microsoft.com/en-us/azure/developer/go/

**Comment by stefancsukker** [comment]
https://github.com/Azure-Samples/storage-blobs-go-quickstart/blob/master/storage-quickstart.go
