### ISSUE TITLE
Implement Login in API

### ISSUE THREAD

**Issue by rieglerthomas** [AustrianDataLAB/IndieGameStream#33]
- [x] Validate Token
- [x] Safe ownership in database when uploading a game
- [ ] ~Check ownerhsip when updating a game~ (Will be removed, see #41 )
- [x] Check ownerhsip when deleting a game
- [x] Check ownership when reading a game by id
- [x] read all games return games of the user who is logged in
- [x] Update tests
- [x] Remove not used methods

**Comment by Intrpt** [comment]
https://golang.withcodeexample.com/blog/building-a-golang-gin-api-with-google-oauth/

**Comment by Intrpt** [comment]
https://pkg.go.dev/golang.org/x/oauth2/google

**Comment by Intrpt** [comment]
https://skarlso.github.io/2016/06/12/google-signin-with-go/
