### ISSUE TITLE
fix frontend <-> api communication

### ISSUE THREAD

**Issue by Intrpt** [AustrianDataLAB/IndieGameStream#43]
![image](https://github.com/AustrianDataLAB/IndieGameStream/assets/34034087/a65819f5-5a89-41c6-8df3-72b47e72ad6a)

**Comment by hunxjunedo** [comment]
@Intrpt let me look int o this, kindly assign it to me if open to external contributions.

**Comment by Intrpt** [comment]
Hi @hunxjunedo,
I just solved the issue by settings the cors policy in the api response.
f0bd5da6441d0fc0bd1149718515bc210c82c4db
