### ISSUE TITLE
Create game CRDs from the API

### ISSUE THREAD

**Issue by jalaka** [AustrianDataLAB/IndieGameStream#51]
After a new game has been added to the API create a CRD insatnce of the game on the cluster:

- [x] Create game crd, e.g. kubectl apply -f mario.yaml
- [x] Read the URL of the created frontend e.g. kubectl get crd game-mario-uuid
- [x] Get the kubernetes config somehow

**Comment by Intrpt** [comment]
https://github.com/AustrianDataLAB/IndieGameStream/blob/e83f31e76ee095f71933b02c880f7e385f8adf7d/operator/internal/controller/stream/game_controller.go#L337

**Comment by Intrpt** [comment]
https://github.com/AustrianDataLAB/IndieGameStream/blob/e83f31e76ee095f71933b02c880f7e385f8adf7d/operator/internal/controller/stream/game_controller.go#L307

**Comment by Intrpt** [comment]
https://github.com/AustrianDataLAB/IndieGameStream/blob/e83f31e76ee095f71933b02c880f7e385f8adf7d/operator/api/stream/v1/game_types.go#L45
