### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by rieglerthomas** [AustrianDataLAB/IndieGameStream#64]
- [x] link to value proposition
- [x] add "Target audience" as own subsection
- [x] improve TL;DR? (should be 60s long) (what your startup does and why anyone should care)
- [x] add versioning scheme to README

**Comment by stefancsukker** [comment]
[Project_Value_Proposition.pdf](https://github.com/user-attachments/files/15866095/Project_Value_Proposition.pdf)
